### ISSUE TITLE
Question on ControlTemplates...

### ISSUE THREAD

**Issue by IndianaGary** [ChaseFlorell/Feedback#5]
I reviewed your article, "How and When to use Control Templates in Xamarin Forms", and also your article, "Realtime Validation in Xamarin Forms with FluentValidation". Both of them have helped me tremendously build a tailored implementation of the latter (a few changes were required because of some breaking changes to FluentValidation, plus I have a similar but different ViewModelBase class hierarchy.) 

I have run into one issue I've been so far unable to resolve: I have a number of EntryEx controls (my version of your ExtendedEntry control) on a view (page); several are required. There is nothing in the logic to detect someone NOT filling out a field. Validation ONLY occurs when SetProperty is called. If a user NEVER touches a field, it is never validated. I had hoped to use the Unfocused event of Entry to force validation but keep getting InvalidOperationExceptions because the Entry is in a ControlTemplate. I tried using an EventToCommandBehavior inside the custom control but ran into the same problem.

Any thoughts come to mind?

Thanks in advance for anything you might be able to provide,

Gary

**Comment by IndianaGary** [comment]
Chase,  I gave since been able to resolve my problem and the code works well. If you are interested in the modifications I made, please reply and I'll see that you get them...

Regards,
Gary

**Comment by ChaseFlorell** [comment]
Hey Gary, I'm glad you got it resolved. I took an extended hiatus from all things open source, thanks for your understanding!
